environment:
    AccessTokenDokanDoc:
      secure: Z8Htovf0nHmWVj+JNOF4H7ozQ5+sS3TkgUu+nyVU414AUlog4kzBhxCSJxIl5t+I

version: 1.0.0-{build}
configuration:
- Release
- Debug
os: Visual Studio 2015
branches:
  only:
    - master

install:
 - ps: |
     Add-Type -AssemblyName System.IO.Compression.FileSystem
            (new-object System.Net.WebClient).DownloadFile(
              'https://github.com/dokan-dev/dokany/releases/download/v1.0.0-RC4/DokanSetup.exe',
              'C:\projects\dokan-dotnet\DokanSetup.exe'
            )
            
      & choco install doxygen.portable
 - cmd: |
     C:\projects\dokan-dotnet\DokanSetup.exe /quiet

before_build:
  - nuget restore
build:
  project: DokanNet.sln
  verbosity: minimal
after_build:
  - ps: |
      $app = Start-Process -passthru .\sample\DokanNetMirror\bin\$env:CONFIGURATION\DokanNetMirror.exe
      Start-Sleep -s 5
      
      git clone https://github.com/Liryna/winfstest.git
      $buildCmd = "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe"
      $buildArgs = @(
      ".\winfstest\winfstest.sln",
      "/m",
      "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
      "/p:Configuration=Debug",
      "/p:Platform=x64")
      
      New-Item C:\TMP -type directory
      & $buildCmd $buildArgs
      & .\winfstest\TestSuite\run-winfstest.bat t N:\TMP
      Start-Sleep -s 5
      Stop-Process $app.Id
test:
  categories:
    except:
      - Manual
      - Timing
      
on_success:
    - ps: |
          if ($env:CONFIGURATION -eq "Release") {
              if ("$env:APPVEYOR_PULL_REQUEST_TITLE" -or "$env:APPVEYOR_REPO_BRANCH" -ne "master") {
                return;
              }
              
              cd $env:APPVEYOR_BUILD_FOLDER\DokanNet\documentations
              git config --global user.email "appveyor@appveyor.org"
              git config --global user.name "appveyor"
              git.exe clone -b gh-pages --single-branch  https://$($env:AccessTokenDokanDoc)@github.com/dokan-dev/dokan-dotnet-doc.git doc
              doxygen.exe Doxyfile
              cd doc
              if ($(git status --porcelain)) {
                Write-Host "Update documentation..." -ForegroundColor Green
                git add -A
                git commit -m "Latest documentation on successful appveyor build $env:APPVEYOR_BUILD_VERSION auto-pushed to gh-pages"
                git push -fq origin gh-pages
                Write-Host "Documentation updated!" -ForegroundColor Green
              } else {
                Write-Host "No documentation changes detected." -ForegroundColor Green
              }
          }
